validation:
  "null":
    enabled: true

  duplicate:
    enabled: true

  datatype:
    enabled: true
    columns:
      salary: float
      performance_rating: int

  regex:
    - column: email
      pattern: EMAIL

    - column: phone
      pattern: PHONE
